namespace Satistools.GameData;

/// <summary>
/// Represents an in-game recipe.
/// </summary>
public class Recipe
{
    /// <summary>
    /// A single part of recipe for production.
    /// </summary>
    public class Part
    {
        /// <summary>
        /// Needed/produced item.
        /// </summary>
        public Item Item { get; set; } = null!;
        
        /// <summary>
        /// Amount of item needed/produced.
        /// </summary>
        public int Amount { get; set; }
    }
    
    /// <summary>
    /// TODO: Descibe class name.
    /// </summary>
    public string ClassName { get; set; } = string.Empty;
    
    /// <summary>
    /// Full name of recipe.
    /// </summary>
    public string DisplayName { get; set; } = string.Empty;

    /// <summary>
    /// List of ingredients needed by recipe.
    /// </summary>
    public Part[] Ingredients { get; set; } = Array.Empty<Part>();

    /// <summary>
    /// List of products generated by recipe.
    /// </summary>
    public Part[] Products { get; set; } = Array.Empty<Part>();
    
    public float ManufacturingDuration { get; set; }
    
    public float ManualManufacturingMultiplier { get; set; }
}