using Satistools.GameData.Items;

namespace Satistools.GameData.Recipes;

/// <summary>
/// Description of product generated by the recipe.
/// </summary>
public class RecipeProduct
{
    public string RecipeId { get; set; } = string.Empty;
    public string ItemId { get; set; } = string.Empty;
    
    /// <summary>
    /// How many items are produced by the recipe.
    /// </summary>
    public int Amount { get; set; }

    public Recipe Recipe { get; set; } = null!;
    public Item Item { get; set; } = null!;

    /// <summary>
    /// Returns how many products are created per minut.
    /// </summary>
    public float PerMin => Recipe.PerMin * Amount;
}